[package]
name = "tool"
version = "0.1.0"
authors = ["Jonathan Giroux <giroux.jo@gmail.com>"]
edition = "2018"

[dependencies]
cfg = { package = "config", version = "0.9" }
dirs = "2.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
tera = "0.11"
